services:
  uppy-discord:
    container_name: uppy-discord
    network_mode: host
    build:
      args:
        - APP_ENV=dev
      dockerfile: ./docker/images/discord/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "0.0.0.0:9001:9001"
    restart: always
  
  uppy-server:
    container_name: uppy-server
    network_mode: host
    build:
      args:
       - APP_ENV=dev
      dockerfile: ./docker/images/server/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
    restart: always

  uppy-telegram:
    container_name: uppy-telegram
    network_mode: host
    build:
      args:
       - APP_ENV=dev
      dockerfile: ./docker/images/telegram/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
    restart: always
    

  uppy-redis:
    container_name: uppy-redis
    restart: always
    image: redis:8.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  uppy-rabbitmq:
    container_name: uppy-rabbitmq
    image: rabbitmq:4.1.4-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  uppy-mongo:
    image: mongo:7.0.9-jammy
    container_name: uppy-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
