services:
  uppy-bot:
    container_name: uppy-bot
    network_mode: host
    build:
      args:
        - APP_ENV=dev
      dockerfile: ./bot/Dockerfile
    volumes:
      - ./bot:/app
    ports:
      - "0.0.0.0:9001:9001"
    restart: always
    depends_on:
      - uppy-backend

  uppy-backend:
    container_name: uppy-backend
    network_mode: host
    build:
      args:
        - APP_ENV=dev
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8088:8088"
    restart: always
    depends_on:
      - uppy-mongo

  uppy-frontend:
    container_name: uppy-frontend
    build:
      args:
        - APP_ENV=dev
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - uppy-backend

  uppy-rabbitmq:
    container_name: uppy-rabbitmq
    image: rabbitmq:4.1.4-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  uppy-mongo:
    image: mongo:7.0.9-jammy
    container_name: uppy-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
volumes:
  mongo_data:
    driver: local
