services:
  fear-bot:
    container_name: fear-bot
    network_mode: host
    build:
      args:
        - APP_ENV=$APP_ENV
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "0.0.0.0:9001:9001"
    environment:
      - MONGO_URL=mongodb://fear-mongo:27017/test?authSource=admin
    env_file: .env
    restart: always
    depends_on:
      - fear-backend

  fear-backend:
    container_name: fear-backend
    build:
      args:
        - APP_ENV=$APP_ENV
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8088:8088"
    environment:
      - MONGO_URL=mongodb://fear-mongo:27017/test?authSource=admin
    env_file: .env
    restart: always
    depends_on:
      - fear-mongo


  fear-mongo:
    image: mongo:7.0.9-jammy
    container_name: fear-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
volumes:
  mongo_data:
    driver: local
