- name: Deploy app
  community.docker.docker_container:
    name: "{{ app_name }}"
    state: started
    image: "{{ app_image }}:{{ app_version }}"
    restart_policy: unless-stopped
    env:
      APP_ENV: prod
      MONGO_URL: "{{ mongo_url }}"
      DISCORD_TOKEN: "{{ discord_token }}"
