$ANSIBLE_VAULT;1.1;AES256
35343039646534316362323565613231636535343937393063303639303136643732303730353239
3534316432343039346138383462663833333062303339310a393735653237633230343461613730
38623665333933323037323363313635653961653934313566323936663332363936343937666161
3665366566643738300a623233663464303737316366383264323539653831393436343538336330
62383738333036633766656561343733613762626635313361303762343266326461633535396333
63623632366632393035313239646332663835336462303735343631386566313631323734613034
38386239336338353164663335323935323762393030636535653636313664616461613063346138
31623262313733633232303336613930613165653434623434383837646164643830323434376465
32353364616463623539353934343062373439653536623736313037386330393966313065356262
38656337363262376563353164353665326261303839353434656131323361393536333233326662
39623438306463363831613062333331666364306166396462383566666530366665303336353539
64323030393261303961383162323131343237376631343936323062316230306131666161626334
64653663636661316338643633306661303830316665663136663132303130343062
