$ANSIBLE_VAULT;1.1;AES256
63306230663031633030633662623263386662666335663733363739336536363237626632383766
3938383063326235616530383262643665363266376332630a386432386338623832313737653730
66323563626561303138616237613234373136313461383233626337623964306630373231316537
6132363830366462380a343163396138313832346564313263623532653830623336666564373139
32356466303835613638333338323433373464353364666436653064636339666665643837316239
64373564316364643935613162363462343734316239386539393232633763656161323662366431
65646532353066373335653936656532393431656337613733623534626166343230396262666237
34653336333639363831613262326363653937623938303039366536343632616163333533336635
33663930323331656439303631303238643164333131343662363130313532636263336666373731
34633062356531626262376638636333393631613832373236323633396531366137656663376139
36363362383666316364343236383735343937303637666562306236313039383732343737373533
33366339663036636463623337633765623065663638353631656637356331393131633538646437
33316537313062653466663463303931313936613434643338303137353161643437376430393661
63653064383764663330333137326635626232303233373838306531343131303562636438326436
30363331393935396230626539633033666363653231303338393939666530373430663132376563
39636531323638326361336437303133616238633863323965343736376564613033363563346336
34323132326533646537353433343133616230633661613464336530636530386535343934316566
37363036623430323232663038643738656564303864646632333830353132326563303538396637
62363432353539326662656430616261653833396462643864663836656666623965343330626630
64643830383765633061
