$ANSIBLE_VAULT;1.1;AES256
35373435393032623533323633633139336261326166303536326638313230666664613031303238
3961613361653635313232313435663933326231663830630a646266323431626366383264396362
37336232303261623562383764326130376630393538666663616664373137633165616635363566
3239376337333266340a323662613661646635306165653734393534333132393634623334376234
65363437343062316634323933316339623962333839363232346130616562306437643434323139
39393962316538376432393864663161393135356565643465663065333136623530656465363732
66363265376364376566383766356337663532636539656632366433306365396563346236636461
39363439623163306364333431363139323832376230343561373138333362343263326138666462
34346164636539393436356235386165333531623532363064366430316363373439346366373038
61303131313063386234623261353866323235646663616335343234383436643063323333653062
66316566306439336439363932336462643862643337633330396239373935353532316234313531
62666432313762356337356463633730316562383066353635373039303033653932383035383335
39306365623563346363346134356339376635313539643266663630303738313864303962383566
31383936303761313434653630373232303061666233646234326131626462623565636432333966
366363326366643964386431346662326265
