mongo_url: "mongodb+srv://pvashkaa:eCRZb2IT2B759u8R@cluster0.o8dn9ca.mongodb.net/Helper-Bot"
registry_username: "a2yomidiscord@gmail.com"
registry_token: "glpat-SqymKSVY0Rb00yOWxhvxF286MQp1OmR3b3kzCw.01.120a2uxi2"
secret_key: 