- name: Deploy app
  community.docker.docker_container:
    name: "{{ app_name }}"
    state: started
    image: "{{ app_image }}:{{ app_version }}"
    restart_policy: unless-stopped
    ports:
      - "8088:8088"
    env:
      APP_ENV: prod
      MONGO_URL: "{{ mongo_url }}"
      SECRET_KEY: "{{ secret_key }}"
      JWT_SECRET: "{{ jwt_secret }}"
      REDIRECT_URI: "{{ redirect_uri }}"
      CLIENT_ID: "{{ client_id }}"
      CLIENT_SECRET: "{{ client_secret }}"
