definitions:
  dtos.CreateSettingsDto:
    properties:
      bumpBanRoleId:
        type: string
      bumpRoleIds:
        items:
          type: string
        type: array
      force:
        type: integer
      guildId:
        type: string
      logChannelId:
        type: string
      pingChannelId:
        type: string
      useForceOnly:
        type: boolean
    type: object
  dtos.UpdateSettingsDto:
    properties:
      bumpBanRoleId:
        type: string
      bumpRoleIds:
        items:
          type: string
        type: array
      force:
        maximum: 7200
        type: integer
      logChannelId:
        type: string
      pingChannelId:
        type: string
      useForceOnly:
        type: boolean
    required:
    - bumpBanRoleId
    - bumpRoleIds
    - logChannelId
    - pingChannelId
    - useForceOnly
    type: object
  models.SettingsModel:
    properties:
      bumpBanRoleId:
        type: string
      bumpRoleIds:
        items:
          type: string
        type: array
      createdAt:
        type: string
      force:
        type: integer
      guildId:
        type: string
      id:
        type: string
      logChannelId:
        type: string
      pingChannelId:
        type: string
      updatedAt:
        type: string
      useForceOnly:
        type: boolean
    type: object
  repositories.UserBumps:
    properties:
      bump:
        type: integer
      like:
        type: integer
      points:
        type: integer
      up:
        type: integer
    type: object
  responses.BadRequestError:
    properties:
      message:
        type: string
    type: object
  responses.InternalError:
    properties:
      message:
        type: string
    type: object
  responses.NotFoundError:
    properties:
      message:
        type: string
    type: object
  responses.ValidationError:
    properties:
      message:
        type: string
      violations:
        items:
          $ref: '#/definitions/responses.Violation'
        type: array
    type: object
  responses.Violation:
    properties:
      message:
        type: string
      propertyPath:
        type: string
    type: object
info:
  contact: {}
  description: Helper bot API
  title: Helper API
  version: "1.0"
paths:
  /api/bumps/{guildId}/{userId}:
    get:
      consumes:
      - application/json
      description: Retrieves bump statistics for a user within date range
      parameters:
      - description: Guild ID
        in: path
        name: guildId
        required: true
        type: string
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Start date
        format: date
        in: query
        name: from
        required: true
        type: string
      - description: End date
        format: date
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repositories.UserBumps'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.NotFoundError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.InternalError'
      security:
      - ApiKeyAuth: []
      summary: Get user bumps statistics
      tags:
      - bumps
  /api/settings:
    post:
      consumes:
      - application/json
      parameters:
      - description: Settings data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateSettingsDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SettingsModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.BadRequestError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.InternalError'
      security:
      - ApiKeyAuth: []
      summary: Create settings if not existed
      tags:
      - settings
  /api/settings/{guildId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Guild ID
        in: path
        name: guildId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SettingsModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.NotFoundError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.InternalError'
      security:
      - ApiKeyAuth: []
      summary: Finds or create settings
      tags:
      - settings
    put:
      consumes:
      - application/json
      parameters:
      - description: Guild ID
        in: path
        name: guildId
        required: true
        type: string
      - description: Settings data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateSettingsDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SettingsModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.NotFoundError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.InternalError'
      security:
      - ApiKeyAuth: []
      summary: Create settings if not existed
      tags:
      - settings
securityDefinitions:
  ApiKeyAuth:
    description: API Key authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
