name: Deploy backend to prod

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/deploy_backend.yml
      - deploy/backend/**
      - docker/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: |
            registry.gitlab.com/ayomits/fear-helper:api_latest
            registry.gitlab.com/ayomits/fear-helper:api
          build-args:
            APP_ENV=prod
          no-cache: true
      
      - name: Trigger Dokploy Deployment
        run: |
          curl -X 'POST' \
          'http://31.13.208.85:3000/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "OnkkhOzAx_s7fP1Sokgqq?tab=general"
              }
          }'
